DROP TABLE IF EXISTS `t_specialty`;

CREATE TABLE `t_specialty` (
  `id` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB;

INSERT INTO `t_specialty` VALUES 
('S001', 'allergologie'),
('S002', 'immunologie'),
('S003', 'anesthésiologie'),
('S004', 'andrologie'),
('S005', 'cardiologie'),
('S006', 'chirurgie cardiaque'),
('S007', 'chirurgie esthétique, plastique et reconstructive'),
('S008', 'chirurgie générale'),
('S009', 'chirurgie maxillo-faciale'),
('S010', 'chirurgie pédiatrique'),
('S011', 'chirurgie thoracique'),
('S012', 'chirurgie vasculaire'),
('S013', 'neurochirurgie'),
('S014', 'dermatologie'),
('S015', 'endocrinologie'),
('S016', 'gastro-entérologie'),
('S017', 'gériatrie'),
('S018', 'gynécologie'),
('S019', 'hématologie'),
('S020', 'hépatologie'),
('S021', 'infectiologie'),
('S022', 'médecine aiguë'),
('S023', 'médecine du travail'),
('S024', 'médecine générale'),
('S025', 'médecine interne'),
('S026', 'médecine nucléaire'),
('S027', 'médecine palliative'),
('S028', 'médecine physique'),
('S029', 'médecine préventive'),
('S030', 'néonatologie'),
('S031', 'néphrologie'),
('S032', 'neurologie'),
('S033', 'odontologie'),
('S034', 'oncologie'),
('S035', 'obstétrique'),
('S036', 'ophtalmologie'),
('S037', 'orthopédie'),
('S038', 'oto-rhino-laryngologie'),
('S039', 'pédiatrie'),
('S040', 'pneumologie'),
('S041', 'psychiatrie'),
('S042', 'radiologie'),
('S043', 'radiothérapie'),
('S044', 'rhumatologie'),
('S045', 'urologie');
