insert into t_medical_act(id, description) values ('HBQK303', 'Radiographies intrabuccales rétroalvéolaires sur un secteur de 1 à 3 dents contigües préinterventionnelle, perinterventionnelle et finale pour acte thérapeutique endodontique')
insert into t_medical_act(id, description) values ('HBQK331', 'Radiographies intrabuccales rétroalvéolaires et/ou rétrocoronaires de 3 secteurs distincts de 1 à 3 dents contigües')
insert into t_medical_act(id, description) values ('HBQK389', 'Radiographie intrabuccale rétroalvéolaire et/ou rétrocoronaire d''un secteur de 1 à 3 dents contigües')
insert into t_medical_act(id, description) values ('HBQK424', 'Radiographies intrabuccales rétroalvéolaires et/ou rétrocoronaires de 11 secteurs distincts de 1 à 3 dents contigües')
insert into t_medical_act(id, description) values ('HBQK428', 'Radiographies intrabuccales rétroalvéolaires et/ou rétrocoronaires de 5 secteurs distincts de 1 à 3 dents contigües')
insert into t_medical_act(id, description) values ('HBQK430', 'Radiographies intrabuccales rétroalvéolaires et/ou rétrocoronaires de 7 secteurs distincts de 1 à 3 dents contigües')
insert into t_medical_act(id, description) values ('HBQK443', 'Radiographies intrabuccales rétroalvéolaires et/ou rétrocoronaires de 4 secteurs distincts de 1 à 3 dents contigües')
insert into t_medical_act(id, description) values ('HBQK476', 'Radiographies intrabuccales rétroalvéolaires et/ou rétrocoronaires de 12 secteurs distincts de 1 à 3 dents contigües')
insert into t_medical_act(id, description) values ('HBQK480', 'Radiographies intrabuccales rétroalvéolaires et/ou rétrocoronaires de 6 secteurs distincts de 1 à 3 dents contigües')
insert into t_medical_act(id, description) values ('HBSD001', 'Hémostase gingivoalvéolaire secondaire à une avulsion dentaire')
insert into t_medical_act(id, description) values ('HCAE192', 'Dilatation unilatérale ou bilatérale de sténose du conduit de plusieurs glandes salivaires par endoscopie [sialendoscopie]')
insert into t_medical_act(id, description) values ('HCAE201', 'Dilatation de sténose du conduit d''une glande salivaire par endoscopie [sialendoscopie] ')
insert into t_medical_act(id, description) values ('HCCA001', 'Dérivation du conduit parotidien [de Sténon] pour suppléance lacrymale')
insert into t_medical_act(id, description) values ('HCCA002', 'Suture de plaie de conduit salivaire')
insert into t_medical_act(id, description) values ('HCCD001', 'Dérivation oropharyngée bilatérale du conduit parotidien [de Sténon], par voie buccale')
insert into t_medical_act(id, description) values ('HCEA001', 'Transposition unilatérale ou bilatérale des conduits submandibulaires [de Wharton]')
insert into t_medical_act(id, description) values ('HCFA001', 'Exérèse de glande submandibulaire [Submandibulectomie] [Sousmaxillectomie] élargie à sa loge, par abord cervicofacial')
insert into t_medical_act(id, description) values ('HCFA002', 'Parotidectomie totale avec résection du nerf facial')
insert into t_medical_act(id, description) values ('HCFA003', 'Exérèse de glande sublinguale, par abord direct')
insert into t_medical_act(id, description) values ('HCFA004', 'Parotidectomie partielle sans dissection du nerf facial')
