insert into t_specialty(id, description) values('S001', 'allergologie')
insert into t_specialty(id, description) values('S002', 'immunologie')
insert into t_specialty(id, description) values('S003', 'anesthésiologie')
insert into t_specialty(id, description) values('S004', 'andrologie')
insert into t_specialty(id, description) values('S005', 'cardiologie')
insert into t_specialty(id, description) values('S006', 'chirurgie cardiaque')
insert into t_specialty(id, description) values('S007', 'chirurgie esthétique, plastique et reconstructive')
insert into t_specialty(id, description) values('S008', 'chirurgie générale')
insert into t_specialty(id, description) values('S009', 'chirurgie maxillo-faciale')
insert into t_specialty(id, description) values('S010', 'chirurgie pédiatrique')
insert into t_specialty(id, description) values('S011', 'chirurgie thoracique')
insert into t_specialty(id, description) values('S012', 'chirurgie vasculaire')
insert into t_specialty(id, description) values('S013', 'neurochirurgie')
insert into t_specialty(id, description) values('S014', 'dermatologie')
insert into t_specialty(id, description) values('S015', 'endocrinologie')
insert into t_specialty(id, description) values('S016', 'gastro-entérologie')
insert into t_specialty(id, description) values('S017', 'gériatrie')
insert into t_specialty(id, description) values('S018', 'gynécologie')
insert into t_specialty(id, description) values('S019', 'hématologie')
insert into t_specialty(id, description) values('S020', 'hépatologie')
insert into t_specialty(id, description) values('S021', 'infectiologie')
insert into t_specialty(id, description) values('S022', 'médecine aiguë')
insert into t_specialty(id, description) values('S023', 'médecine du travail')
insert into t_specialty(id, description) values('S024', 'médecine générale')
insert into t_specialty(id, description) values('S025', 'médecine interne')
insert into t_specialty(id, description) values('S026', 'médecine nucléaire')
insert into t_specialty(id, description) values('S027', 'médecine palliative')
insert into t_specialty(id, description) values('S028', 'médecine physique')
insert into t_specialty(id, description) values('S029', 'médecine préventive')
insert into t_specialty(id, description) values('S030', 'néonatologie')
insert into t_specialty(id, description) values('S031', 'néphrologie')
insert into t_specialty(id, description) values('S032', 'neurologie')
insert into t_specialty(id, description) values('S033', 'odontologie')
insert into t_specialty(id, description) values('S034', 'oncologie')
insert into t_specialty(id, description) values('S035', 'obstétrique')
insert into t_specialty(id, description) values('S036', 'ophtalmologie')
insert into t_specialty(id, description) values('S037', 'orthopédie')
insert into t_specialty(id, description) values('S038', 'oto-rhino-laryngologie')
insert into t_specialty(id, description) values('S039', 'pédiatrie')
insert into t_specialty(id, description) values('S040', 'pneumologie')
insert into t_specialty(id, description) values('S041', 'psychiatrie')
insert into t_specialty(id, description) values('S042', 'radiologie')
insert into t_specialty(id, description) values('S043', 'radiothérapie')
insert into t_specialty(id, description) values('S044', 'rhumatologie')
insert into t_specialty(id, description) values('S045', 'urologie')
