insert into t_disease(id, description) values ('J00', 'Rhinopharyngite (aiguë) [rhume banal]')
insert into t_disease(id, description) values ('J01', 'Sinusite aiguë')
insert into t_disease(id, description) values ('J010', 'Sinusite maxillaire aiguë')
insert into t_disease(id, description) values ('J011', 'Sinusite frontale aiguë')
insert into t_disease(id, description) values ('J012', 'Sinusite ethmoïdale aiguë')
insert into t_disease(id, description) values ('J013', 'Sinusite sphénoïdale aiguë')
insert into t_disease(id, description) values ('J014', 'Pansinusite aiguë')
insert into t_disease(id, description) values ('J018', 'Autres sinusites aiguës')
insert into t_disease(id, description) values ('J019', 'Sinusite aiguë, sans précision')
insert into t_disease(id, description) values ('J02', 'Pharyngite aiguë')
insert into t_disease(id, description) values ('J020', 'Pharyngite à streptocoques')
insert into t_disease(id, description) values ('J028', 'Pharyngite aiguë due à d''autres micro-organismes précisés')
insert into t_disease(id, description) values ('J029', 'Pharyngite (aiguë), sans précision')
insert into t_disease(id, description) values ('J03', 'Amygdalite aiguë')
insert into t_disease(id, description) values ('J030', 'Amygdalite à steptocoques')
insert into t_disease(id, description) values ('J038', 'Amygdalite aiguë due à d''autres micro-organismes précisés')
insert into t_disease(id, description) values ('J039', 'Amygdalite (aiguë), sans précision')
insert into t_disease(id, description) values ('J04', 'Laryngite et trachéite aiguës')
insert into t_disease(id, description) values ('J040', 'Laryngite (aiguë)')
insert into t_disease(id, description) values ('J041', 'Trachéite (aiguë)')
